### ISSUE TITLE
refactor!: changing databases to MongoDB

### ISSUE THREAD

**Issue by DEV-DIBSTER** [DanBot-Hosting/DanBotHostingStats#460]
This would be a time consuming project, but it would start changing the database for the Discord Bot from a local database (quick.db) and uses purely MongoDB.

Benefits:
- Reducing the need to compile sqlite3, allowing the bot to more easily be reinstalled.
- Increases validation for new objects.
- Would fix several issues with the current database.

**Comment by wdhdev** [comment]
I don't see the point of any of this. Just move all the panel-related and dono-related stuff to the beta bot. It already uses MongoDB and migrating the data wouldn't be that hard.

**Comment by DEV-DIBSTER** [comment]
> I don't see the point of any of this. Just move all the panel-related and dono-related stuff to the beta bot. It already uses MongoDB and migrating the data wouldn't be that hard.

Up to people if they want to use slash commands. 🤷‍♂️

**Comment by JustArtiom** [comment]
Discord added slash commands for a reason. Everyone should get used to it

**Comment by wdhdev** [comment]
This ^^

**Comment by lajczi** [comment]
> I don't see the point of any of this. Just move all the panel-related and dono-related stuff to the beta bot. It already uses MongoDB and migrating the data wouldn't be that hard.

I agree with you
